<a href="https://colab.research.google.com/github/seiyanbelltree/MLpractice/blob/master/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch

In [6]:
a = torch.tensor([1,2,3])
print(a, type(a))

tensor([1, 2, 3]) <class 'torch.Tensor'>


In [9]:
b = torch.tensor([[1,2],
                 [3,4]])

In [12]:
c = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]], dtype=torch.float64)
c

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

In [14]:
d = torch.arange(0,10)
d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
e = torch.zeros(2,3)
e

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
f = torch.rand(2,3)
print(f, type(f), f.size())

tensor([[0.3702, 0.6067, 0.3605],
        [0.9473, 0.2655, 0.4130]]) <class 'torch.Tensor'> torch.Size([2, 3])


In [32]:
g = torch.tensor([1,2,3])
#Tensor to Numpy
g = g.numpy()
type(g)

numpy.ndarray

In [33]:
#Numpy to Tensor
g = torch.from_numpy(g)
type(g)

torch.Tensor

### 範囲指定



In [57]:
a = torch.tensor([
                  [0,1,2],
                  [3,4,5],
                  [6,7,8]
])
print(a[1,1])
print(a[:,:])
print(a[:1,2:])
print(a[1, [0,2]])
print(a[a>3])

tensor(4)
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[2]])
tensor([3, 5])
tensor([4, 5, 6, 7, 8])


In [58]:
a[0,2] = 11
print(a)

tensor([[ 0,  1, 11],
        [ 3,  4,  5],
        [ 6,  7,  8]])


In [59]:
a[:,2] = 22
print(a)

tensor([[ 0,  1, 22],
        [ 3,  4, 22],
        [ 6,  7, 22]])


In [60]:
a[a<10] = 33
print(a)

tensor([[33, 33, 22],
        [33, 33, 22],
        [33, 33, 22]])


### ベクトルの計算

In [61]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = torch.tensor([
                  [6,7,8],
                  [9,10,11]
])

In [67]:
print(a + 3)
print(a + b)
print(c + 2)
print(c + a)
print(c + c)

tensor([4, 5, 6])
tensor([5, 7, 9])
tensor([[ 8,  9, 10],
        [11, 12, 13]])
tensor([[ 7,  9, 11],
        [10, 12, 14]])
tensor([[12, 14, 16],
        [18, 20, 22]])


### 様々な値の計算

In [71]:
a = torch.tensor([
                  [1,2,3],
                  [4,5,6.0]
])
m = torch.mean(a)
print(m.item())

3.5


In [72]:
m2 = a.mean()
print(m.item())

3.5


In [74]:
#引数は軸の向き（axisのようなもの）
print(a.mean(0))
print(a.mean(1))

tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])


In [75]:
print(torch.sum(a).item())

21.0


In [76]:
print(torch.max(a).item())

6.0


In [77]:
print(torch.min(a).item())

1.0


### 演習

In [78]:
a = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.float64)
b = torch.tensor([1,2,3], dtype=torch.float64)

In [81]:
print(a + b)
print(a - b)

tensor([[2., 4., 6.],
        [5., 7., 9.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [3., 3., 3.]], dtype=torch.float64)


In [82]:
print(a * b)
print(a / b)
print(a // b)
print(a % b)

tensor([[ 1.,  4.,  9.],
        [ 4., 10., 18.]], dtype=torch.float64)
